In [49]:
import polars as pl
import numpy as np
import re

In [50]:
path = "C:\\Users\\Arnold\\OneDrive\\Desktop\\CAPSTONE PROJECT\\farming_risk_regions\\data\\interim\\weather_data\\all_locations_weather_data.csv"
weather_data = pl.read_csv(path, try_parse_dates=True)

In [51]:
# Check the schema and first few rows
print(weather_data.schema)
print("\nFirst few rows:")
weather_data.head()

Schema({'location': String, 'date': Date, 'lat_center': Float64, 'lon_center': Float64, 'lat_min': Float64, 'lat_max': Float64, 'lon_min': Float64, 'lon_max': Float64, 'ALLSKY_SFC_SW_DWN': Float64, 'PRECTOTCORR': Float64, 'RH2M': Float64, 'T2M_MAX': Float64, 'T2M_MIN': Float64, 'WS10M': Float64})

First few rows:

shape: (5, 14)
┌─────────────────┬────────────┬────────────┬────────────┬───┬───────┬─────────┬─────────┬───────┐
│ location        ┆ date       ┆ lat_center ┆ lon_center ┆ … ┆ RH2M  ┆ T2M_MAX ┆ T2M_MIN ┆ WS10M │
│ ---             ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---   ┆ ---     ┆ ---     ┆ ---   │
│ str             ┆ date       ┆ f64        ┆ f64        ┆   ┆ f64   ┆ f64     ┆ f64     ┆ f64   │
╞═════════════════╪════════════╪════════════╪════════════╪═══╪═══════╪═════════╪═════════╪═══════╡
│ Story_County_IA ┆ 2014-01-01 ┆ 42.025     ┆ -93.5      ┆ … ┆ 77.96 ┆ -13.07  ┆ -17.98  ┆ 6.41  │
│ Story_County_IA ┆ 2014-01-02 ┆ 42.025     ┆ -93.5      ┆ … ┆ 77.08 ┆ -11.63  ┆ -18.55  ┆ 4.37  │
│ Story_County_IA ┆ 2014-01-03 ┆ 42.025     ┆ -93.5      ┆ … ┆ 84.33 ┆ -2.26   ┆ -18.78  ┆ 8.83  │
│ Story_County_IA ┆ 2014-01-04 ┆ 42.025     ┆ -93.5      ┆ … ┆ 72.45 ┆ -1.7    ┆ -12.34  ┆ 8.15  │
│ Story_County_IA ┆ 2014-01-05 ┆ 42.025     ┆ -93.5      ┆ … ┆ 56.36 ┆ -13.14  ┆ -23.8   ┆ 10.53 │
└─────────────────┴────────────┴────────────┴────────────┴───┴───────┴─────────┴─────────┴───────┘

In [52]:
## 
def calculate_weather_variables(dataframe):
    '''
    Function to calculate additional weather variables from the existing data using Polars.

    PRECTOTCORR - Precipitation:
        - ppt_intensity: rainfall intensity (total/rainy days)
        - ppt_variance: precipitation variability
        - rainy_days: number of days with precipitation > 1mm
        
    T2M_MAX, T2M_MIN - Temperature:
        - tmin: mean minimum temperature
        - temp_range: mean diurnal temperature range (Tmax - Tmin)
        - gdd: growing degree days (base 10°C)
        - frost_days: days with Tmin < 0°C
        - stress_days: days with extreme heat (Tmax > 35°C)
        
    WS10M - Wind Speed:
        - wind_mean: average wind speed
        - wind_max: maximum wind speed
        - high_wind_days: days with wind > 10 m/s
        
    ALLSKY_SFC_SW_DWN - Solar Radiation:
        - solar_mean: average solar radiation
        - solar_sum: cumulative solar radiation
        - low_light_days: days with radiation < threshold
        
    RH2M - Relative Humidity:
        - rh_mean: average relative humidity
        - high_humidity_days: days with RH > 90%
        - vpd: vapor pressure deficit (evaporative demand)    
    '''
    
    # Add year and month columns for grouping
    df = dataframe.with_columns([
        pl.col('date').dt.year().alias('year'),
        pl.col('date').dt.month().alias('month')
    ])
    
    # Create monthly aggregated features
    monthly_weather = df.group_by(['location', 'year', 'month']).agg([
        # ===== PRECIPITATION VARIABLES =====
        pl.col('PRECTOTCORR').sum().alias('ppt_total'),
        (pl.col('PRECTOTCORR') > 1).sum().alias('rainy_days'),
        pl.col('PRECTOTCORR').std().alias('ppt_variance'),
        
        # ===== TEMPERATURE VARIABLES =====
        pl.col('T2M_MAX').mean().alias('tmax'),
        pl.col('T2M_MIN').mean().alias('tmin'),
        (pl.col('T2M_MAX') - pl.col('T2M_MIN')).mean().alias('temp_range'),
        
        # Extreme temperature days
        (pl.col('T2M_MAX') > 30).sum().alias('tmax30'),
        (pl.col('T2M_MAX') > 35).sum().alias('tmax35'),
        (pl.col('T2M_MIN') < 0).sum().alias('tmin0'),
        
        # Growing Degree Days (GDD) - base 10°C
        (((pl.col('T2M_MAX') + pl.col('T2M_MIN')) / 2 - 10).clip(lower_bound=0)).sum().alias('gdd'),
        
        # ===== WIND VARIABLES =====
        pl.col('WS10M').mean().alias('wind_mean'),
        pl.col('WS10M').max().alias('wind_max'),
        pl.col('WS10M').std().alias('wind_variance'),
        (pl.col('WS10M') > 10).sum().alias('high_wind_days'),
        
        # ===== SOLAR RADIATION VARIABLES =====
        pl.col('ALLSKY_SFC_SW_DWN').mean().alias('solar_mean'),
        pl.col('ALLSKY_SFC_SW_DWN').sum().alias('solar_sum'),
        pl.col('ALLSKY_SFC_SW_DWN').std().alias('solar_variance'),
        (pl.col('ALLSKY_SFC_SW_DWN') < 115.7).sum().alias('low_light_days'),
        
        # ===== HUMIDITY VARIABLES =====
        pl.col('RH2M').mean().alias('rh_mean'),
        pl.col('RH2M').min().alias('rh_min'),
        pl.col('RH2M').max().alias('rh_max'),
        (pl.col('RH2M') > 90).sum().alias('high_humidity_days'),
        (pl.col('RH2M') < 30).sum().alias('low_humidity_days'),
        
        # ===== COMPOUND INDICES =====
        # Heat-humidity stress
        ((pl.col('T2M_MAX') > 30) & (pl.col('RH2M') > 70)).sum().alias('heat_humidity_stress_days'),
        
        # Drought stress
        ((pl.col('PRECTOTCORR') < 2) & (pl.col('T2M_MAX') > 30) & (pl.col('RH2M') < 40)).sum().alias('drought_stress_days'),
        
        # Storm potential
        ((pl.col('PRECTOTCORR') > 20) & (pl.col('WS10M') > 8)).sum().alias('storm_potential_days'),
        
        # Cloudy warm days
        ((pl.col('T2M_MAX') > 20) & (pl.col('ALLSKY_SFC_SW_DWN') < 150)).sum().alias('cloudy_warm_days'),
    ])
    
    # Calculate derived variables that need the aggregated data
    monthly_weather = monthly_weather.with_columns([
        # Precipitation intensity (total rainfall / rainy days)
        (pl.col('ppt_total') / pl.when(pl.col('rainy_days') > 0).then(pl.col('rainy_days')).otherwise(1)).alias('ppt_intensity'),
        
        # Vapor Pressure Deficit (VPD)
        # VPD = (1 - RH/100) * es(T), where es is saturation vapor pressure
        # Saturation vapor pressure: es = 0.6108 * exp((17.27 * T) / (T + 237.3))
        ((1 - pl.col('rh_mean') / 100) * 
         (0.6108 * (17.27 * (pl.col('tmax') + pl.col('tmin')) / 2 / 
          ((pl.col('tmax') + pl.col('tmin')) / 2 + 237.3)).exp())).alias('vpd_mean')
    ])
    
    return monthly_weather

In [53]:
monthly_weather = calculate_weather_variables(weather_data)
monthly_weather

shape: (1_452, 32)
┌──────────────┬──────┬───────┬───────────┬───┬─────────────┬─────────────┬─────────────┬──────────┐
│ location     ┆ year ┆ month ┆ ppt_total ┆ … ┆ storm_poten ┆ cloudy_warm ┆ ppt_intensi ┆ vpd_mean │
│ ---          ┆ ---  ┆ ---   ┆ ---       ┆   ┆ tial_days   ┆ _days       ┆ ty          ┆ ---      │
│ str          ┆ i32  ┆ i8    ┆ f64       ┆   ┆ ---         ┆ ---         ┆ ---         ┆ f64      │
│              ┆      ┆       ┆           ┆   ┆ u32         ┆ u32         ┆ f64         ┆          │
╞══════════════╪══════╪═══════╪═══════════╪═══╪═════════════╪═════════════╪═════════════╪══════════╡
│ Pottawattami ┆ 2023 ┆ 2     ┆ 45.11     ┆ … ┆ 0           ┆ 0           ┆ 9.022       ┆ 0.156377 │
│ e_County_IA  ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ Pottawattami ┆ 2019 ┆ 10    ┆ 113.16    ┆ … ┆ 0           ┆ 4           ┆ 12.573333   ┆ 0.262398 │
│ e_County_IA  ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ Pottawattami ┆ 2014 ┆ 7     ┆ 66.07     ┆ … ┆ 0           ┆ 31          ┆ 8.25875     ┆ 0.675683 │
│ e_County_IA  ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ Dawson_Count ┆ 2024 ┆ 9     ┆ 5.6       ┆ … ┆ 0           ┆ 30          ┆ 2.8         ┆ 1.432793 │
│ y_NE         ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ Dawson_Count ┆ 2020 ┆ 3     ┆ 56.78     ┆ … ┆ 0           ┆ 6           ┆ 7.0975      ┆ 0.247083 │
│ y_NE         ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ …            ┆ …    ┆ …     ┆ …         ┆ … ┆ …           ┆ …           ┆ …           ┆ …        │
│ Livingston_C ┆ 2021 ┆ 10    ┆ 211.44    ┆ … ┆ 0           ┆ 16          ┆ 15.102857   ┆ 0.327666 │
│ ounty_IL     ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ Champaign_Co ┆ 2021 ┆ 2     ┆ 43.53     ┆ … ┆ 0           ┆ 0           ┆ 7.255       ┆ 0.045273 │
│ unty_IL      ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ Champaign_Co ┆ 2023 ┆ 10    ┆ 97.91     ┆ … ┆ 0           ┆ 13          ┆ 8.900909    ┆ 0.471899 │
│ unty_IL      ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ Livingston_C ┆ 2017 ┆ 6     ┆ 101.77    ┆ … ┆ 0           ┆ 30          ┆ 8.480833    ┆ 0.658304 │
│ ounty_IL     ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
│ LaSalle_Coun ┆ 2018 ┆ 4     ┆ 43.11     ┆ … ┆ 0           ┆ 3           ┆ 5.38875     ┆ 0.223033 │
│ ty_IL        ┆      ┆       ┆           ┆   ┆             ┆             ┆             ┆          │
└──────────────┴──────┴───────┴───────────┴───┴─────────────┴─────────────┴─────────────┴──────────┘

In [54]:
def calculate_anomalies(weather_df: pl.DataFrame, vars: list[str] | None = None, group_cols: list[str] | None = None) -> pl.DataFrame:
    """
    Transform weather variables into standardized anomalies (z-scores) per group.
    x_AN = (x - mean_group) / std_group

    """
    group_cols = ['location', 'month']

    preferred = [
        'ppt_total', 'ppt_intensity', 'ppt_variance',
        'tmax', 'tmin', 'temp_range', 'gdd',
        'tmax30', 'tmax35', 'tmin0',
        'wind_mean', 'wind_max', 'wind_variance', 'high_wind_days',
        'solar_mean', 'solar_sum', 'solar_variance', 'low_light_days',
        'rh_mean', 'rh_min', 'rh_max', 'high_humidity_days', 'low_humidity_days',
        'heat_humidity_stress_days', 'drought_stress_days', 'storm_potential_days', 'cloudy_warm_days',
        'vpd_mean'
    ]
    if vars is None:
        vars = [v for v in preferred if v in weather_df.columns]
    else:
        vars = [v for v in vars if v in weather_df.columns]

    if not vars:
        raise ValueError("No valid variables found to compute anomalies; please pass 'vars' that exist in the DataFrame.")

    # Compute group-wise stats for all variables in a single aggregation
    agg_exprs = []
    for v in vars:
        agg_exprs.append(pl.col(v).mean().alias(f"{v}__mean"))
        agg_exprs.append(pl.col(v).std().alias(f"{v}__std"))

    stats = weather_df.group_by(group_cols).agg(agg_exprs)

    # Join stats back and compute anomalies
    df = weather_df.join(stats, on=group_cols, how='left')

    an_exprs = []
    for v in vars:
        mean_col = pl.col(f"{v}__mean")
        std_col = pl.col(f"{v}__std")
        an_exprs.append(
            pl.when(std_col.fill_null(0).abs() > 0)
            .then((pl.col(v) - mean_col) / std_col)
            .otherwise(pl.lit(0.0))
            .alias(f"{v}_AN")
        )
    df = df.with_columns(an_exprs)

    # Drop helper columns 
    drop_cols = [f"{v}__mean" for v in vars] + [f"{v}__std" for v in vars]
    df = df.drop(drop_cols)

    return df

In [55]:
# Compute anomalies using Polars (grouped by location and month)
anomalies = calculate_anomalies(monthly_weather)
anomalies.head()

shape: (5, 60)
┌─────────────┬──────┬───────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ location    ┆ year ┆ month ┆ ppt_total ┆ … ┆ drought_str ┆ storm_poten ┆ cloudy_war ┆ vpd_mean_A │
│ ---         ┆ ---  ┆ ---   ┆ ---       ┆   ┆ ess_days_AN ┆ tial_days_A ┆ m_days_AN  ┆ N          │
│ str         ┆ i32  ┆ i8    ┆ f64       ┆   ┆ ---         ┆ N           ┆ ---        ┆ ---        │
│             ┆      ┆       ┆           ┆   ┆ f64         ┆ ---         ┆ f64        ┆ f64        │
│             ┆      ┆       ┆           ┆   ┆             ┆ f64         ┆            ┆            │
╞═════════════╪══════╪═══════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Pottawattam ┆ 2023 ┆ 2     ┆ 45.11     ┆ … ┆ 0.0         ┆ 0.0         ┆ -0.301511  ┆ 0.56957    │
│ ie_County_I ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ A           ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Pottawattam ┆ 2019 ┆ 10    ┆ 113.16    ┆ … ┆ -0.301511   ┆ -0.301511   ┆ -1.411588  ┆ -0.896625  │
│ ie_County_I ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ A           ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Pottawattam ┆ 2014 ┆ 7     ┆ 66.07     ┆ … ┆ 0.0         ┆ -0.301511   ┆ 0.301511   ┆ -0.987505  │
│ ie_County_I ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ A           ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Dawson_Coun ┆ 2024 ┆ 9     ┆ 5.6       ┆ … ┆ 0.793329    ┆ 0.0         ┆ 0.911414   ┆ 1.647483   │
│ ty_NE       ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Dawson_Coun ┆ 2020 ┆ 3     ┆ 56.78     ┆ … ┆ 0.0         ┆ -0.421741   ┆ 0.709255   ┆ -0.849359  │
│ ty_NE       ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────┴───────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [56]:
def create_lagged_features(df: pl.DataFrame, lag_months: list[int]) -> pl.DataFrame:

    lagged_dataframe= df.clone()
    vars = [col for col in df.columns if col.endswith('_AN')]

    for var in vars:
        for lag in lag_months:
            lagged_dataframe = lagged_dataframe.with_columns(
                df.select([pl.col(var).shift(lag).over("location").alias(f"{var}_lag{lag}")])
            )

    return lagged_dataframe

In [57]:
lagged_weather = create_lagged_features(anomalies, lag_months=[1, 2])
lagged_weather = lagged_weather.drop_nulls()
lagged_weather.head()

shape: (5, 116)
┌─────────────┬──────┬───────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ location    ┆ year ┆ month ┆ ppt_total ┆ … ┆ cloudy_warm ┆ cloudy_warm ┆ vpd_mean_A ┆ vpd_mean_A │
│ ---         ┆ ---  ┆ ---   ┆ ---       ┆   ┆ _days_AN_la ┆ _days_AN_la ┆ N_lag1     ┆ N_lag2     │
│ str         ┆ i32  ┆ i8    ┆ f64       ┆   ┆ g1          ┆ g2          ┆ ---        ┆ ---        │
│             ┆      ┆       ┆           ┆   ┆ ---         ┆ ---         ┆ f64        ┆ f64        │
│             ┆      ┆       ┆           ┆   ┆ f64         ┆ f64         ┆            ┆            │
╞═════════════╪══════╪═══════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Pottawattam ┆ 2014 ┆ 7     ┆ 66.07     ┆ … ┆ -1.411588   ┆ -0.301511   ┆ -0.896625  ┆ 0.56957    │
│ ie_County_I ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ A           ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Renville_Co ┆ 2016 ┆ 11    ┆ 38.15     ┆ … ┆ -0.330902   ┆ 0.0         ┆ 0.758847   ┆ 0.624329   │
│ unty_MN     ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Pottawattam ┆ 2018 ┆ 4     ┆ 20.21     ┆ … ┆ 0.301511    ┆ -1.411588   ┆ -0.987505  ┆ -0.896625  │
│ ie_County_I ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ A           ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Champaign_C ┆ 2019 ┆ 9     ┆ 82.1      ┆ … ┆ 0.0         ┆ 0.028339    ┆ -0.088304  ┆ -0.87681   │
│ ounty_IL    ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Story_Count ┆ 2018 ┆ 5     ┆ 102.11    ┆ … ┆ 0.0         ┆ -0.550608   ┆ -1.27548   ┆ -0.415172  │
│ y_IA        ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
└─────────────┴──────┴───────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [58]:
insurance_df = pl.read_csv("C:\\Users\\Arnold\\OneDrive\\Desktop\\CAPSTONE PROJECT\\farming_risk_regions\\data\\interim\\insurance_data\\insurance_data_cleaned.csv", try_parse_dates=True)
insurance_df.tail()

shape: (5, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ commodity ┆ state_cod ┆ state_abb ┆ county_co ┆ … ┆ efa_premi ┆ indemnity ┆ loss_rati ┆ county_s │
│ _year     ┆ e         ┆ reviation ┆ de        ┆   ┆ um_discou ┆ _amount   ┆ o         ┆ tate     │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ nt        ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ str       ┆ i64       ┆   ┆ ---       ┆ i64       ┆ f64       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 5350      ┆ 0.03      ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 3508      ┆ 5.65      ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
│ 2025      ┆ 56        ┆ WY        ┆ 45        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ Weston,W │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Y        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [59]:
## Filtering the location in the insurance data to match with weather data
common_locations = lagged_weather.select("location").unique().to_series().to_list()
common_locations

['Webster_County_IA',
 'Renville_County_MN',
 'Champaign_County_IL',
 'McLean_County_IL',
 'Dawson_County_NE',
 'Pottawattamie_County_IA',
 'Livingston_County_IL',
 'LaSalle_County_IL',
 'Saline_County_MO',
 'Iroquois_County_IL',
 'Story_County_IA']

In [60]:
list_locations = []
for i in common_locations:
    i = re.sub("_", "",i)
    i = re.sub(r'County',r",",i)
    list_locations.append(i)

In [61]:
list_locations

['Webster,IA',
 'Renville,MN',
 'Champaign,IL',
 'McLean,IL',
 'Dawson,NE',
 'Pottawattamie,IA',
 'Livingston,IL',
 'LaSalle,IL',
 'Saline,MO',
 'Iroquois,IL',
 'Story,IA']

In [62]:
insurance_df.columns

['commodity_year',
 'state_code',
 'state_abbreviation',
 'county_code',
 'county_name',
 'commodity_code',
 'commodity_name',
 'insurance_plan_code',
 'insurance_plan_abbreviation',
 'coverage_category',
 'delivery_type',
 'coverage_level',
 'policies_sold_count',
 'policies_earning_premium_count',
 'policies_indemnified_count',
 'units_earning_premium_count',
 'units_indemnified_count',
 'quantity_type',
 'net_reported_quantity',
 'endorsed_companion_acres',
 'liability_amount',
 'total_premium_amount',
 'subsidy_amount',
 'state_private_subsidy',
 'additional_subsidy',
 'efa_premium_discount',
 'indemnity_amount',
 'loss_ratio',
 'county_state']

In [63]:
## Filtering the location in the insurance data to match with weather data
filtered_insurance = (
    insurance_df
    .filter(pl.col("county_state").is_in(list_locations))
    .with_columns(pl.col("commodity_name").str.strip_chars(" ").alias("commodity_name"))
    .filter(pl.col("commodity_name") == "Corn")
    .select(['commodity_year', 'loss_ratio', 'county_state','net_reported_quantity'])
)
filtered_insurance.head()

shape: (5, 4)
┌────────────────┬────────────┬──────────────────┬───────────────────────┐
│ commodity_year ┆ loss_ratio ┆ county_state     ┆ net_reported_quantity │
│ ---            ┆ ---        ┆ ---              ┆ ---                   │
│ i64            ┆ f64        ┆ str              ┆ i64                   │
╞════════════════╪════════════╪══════════════════╪═══════════════════════╡
│ 2014           ┆ 3.09       ┆ Pottawattamie,IA ┆ 91                    │
│ 2014           ┆ 0.0        ┆ Pottawattamie,IA ┆ 12                    │
│ 2014           ┆ 4.74       ┆ Pottawattamie,IA ┆ 1049                  │
│ 2014           ┆ 2.87       ┆ Pottawattamie,IA ┆ 3923                  │
│ 2014           ┆ 4.42       ┆ Pottawattamie,IA ┆ 23697                 │
└────────────────┴────────────┴──────────────────┴───────────────────────┘

In [64]:
filtered_insurance.shape

(2144, 4)

In [65]:
fixed_lagged_weather = lagged_weather.with_columns(pl.col("location").str.replace("County", ",").str.replace_all("_", ""))
fixed_lagged_weather

shape: (1_430, 116)
┌─────────────┬──────┬───────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ location    ┆ year ┆ month ┆ ppt_total ┆ … ┆ cloudy_warm ┆ cloudy_warm ┆ vpd_mean_A ┆ vpd_mean_A │
│ ---         ┆ ---  ┆ ---   ┆ ---       ┆   ┆ _days_AN_la ┆ _days_AN_la ┆ N_lag1     ┆ N_lag2     │
│ str         ┆ i32  ┆ i8    ┆ f64       ┆   ┆ g1          ┆ g2          ┆ ---        ┆ ---        │
│             ┆      ┆       ┆           ┆   ┆ ---         ┆ ---         ┆ f64        ┆ f64        │
│             ┆      ┆       ┆           ┆   ┆ f64         ┆ f64         ┆            ┆            │
╞═════════════╪══════╪═══════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ Pottawattam ┆ 2014 ┆ 7     ┆ 66.07     ┆ … ┆ -1.411588   ┆ -0.301511   ┆ -0.896625  ┆ 0.56957    │
│ ie,IA       ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Renville,MN ┆ 2016 ┆ 11    ┆ 38.15     ┆ … ┆ -0.330902   ┆ 0.0         ┆ 0.758847   ┆ 0.624329   │
│ Pottawattam ┆ 2018 ┆ 4     ┆ 20.21     ┆ … ┆ 0.301511    ┆ -1.411588   ┆ -0.987505  ┆ -0.896625  │
│ ie,IA       ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Champaign,I ┆ 2019 ┆ 9     ┆ 82.1      ┆ … ┆ 0.0         ┆ 0.028339    ┆ -0.088304  ┆ -0.87681   │
│ L           ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Story,IA    ┆ 2018 ┆ 5     ┆ 102.11    ┆ … ┆ 0.0         ┆ -0.550608   ┆ -1.27548   ┆ -0.415172  │
│ …           ┆ …    ┆ …     ┆ …         ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Livingston, ┆ 2021 ┆ 10    ┆ 211.44    ┆ … ┆ 0.0         ┆ 0.0         ┆ -1.398891  ┆ 0.169581   │
│ IL          ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Champaign,I ┆ 2021 ┆ 2     ┆ 43.53     ┆ … ┆ -1.842018   ┆ 0.449467    ┆ -1.533039  ┆ -1.171547  │
│ L           ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Champaign,I ┆ 2023 ┆ 10    ┆ 97.91     ┆ … ┆ -0.53936    ┆ -1.842018   ┆ -1.304604  ┆ -1.533039  │
│ L           ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ Livingston, ┆ 2017 ┆ 6     ┆ 101.77    ┆ … ┆ 0.651753    ┆ 0.0         ┆ -0.556514  ┆ -1.398891  │
│ IL          ┆      ┆       ┆           ┆   ┆             ┆             ┆            ┆            │
│ LaSalle,IL  ┆ 2018 ┆ 4     ┆ 43.11     ┆ … ┆ 0.0         ┆ 0.449467    ┆ -0.666287  ┆ -0.673889  │
└─────────────┴──────┴───────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [66]:
fixed_lagged_weather.write_csv("C:\\Users\\Arnold\\OneDrive\\Desktop\\CAPSTONE PROJECT\\farming_risk_regions\\data\\interim\\weather_data\\lagged_weather_data.csv")

In [67]:
# Merge helper: normalize keys and join monthly (yearly insurance broadcast across months)

def _normalize_weather_key(df: pl.DataFrame) -> pl.DataFrame:
    return df.with_columns([
        pl.col("location")
          .str.to_uppercase()
          .str.replace_all("COUNTY", ",")
          .str.replace_all(r"\\s+", "")   # remove spaces
          .str.replace_all("_", "")         # remove underscores
          .alias("join_key"),
        pl.col("year").cast(pl.Int64)
    ])


def _normalize_insurance_key(df: pl.DataFrame) -> pl.DataFrame:
    base = df
    # Ensure year column present and standardized name
    if "year" not in base.columns:
        base = base.with_columns(pl.col("commodity_year").cast(pl.Int64).alias("year"))
    return base.with_columns([
        pl.col("county_state")
          .str.to_uppercase()
          .str.replace_all(r"\\s+", "")   # 'Story, IA' -> 'STORY,IA'
          .alias("join_key"),
        pl.col("year").cast(pl.Int64)
    ])


def merge_and_prepare_polars(
    weather_df: pl.DataFrame,
    insurance_df: pl.DataFrame,
    join_grain: str = "monthly",   # "monthly" or "annual"
    drop_unmatched: bool = False,
) -> pl.DataFrame:
    """
    Merge insurance and weather data with proper temporal alignment using Polars.

    - monthly: broadcast yearly insurance values across all months of that year per location.
    - annual: aggregate weather to annual per location prior to merge.
    """
    w = _normalize_weather_key(weather_df)
    i = _normalize_insurance_key(insurance_df)

    if join_grain == "annual":
        # Aggregate weather to annual per join_key/year
        # Choose sensible aggregations: sums for totals, means for rates/indices
        sum_cols = [c for c in w.columns if c in {"ppt_total", "gdd", "solar_sum"}]
        # Aggregate all numeric columns by mean unless in sum_cols or are identifiers
        id_cols = {"join_key", "year", "location"}
        num_cols = [c for c, dt in zip(w.columns, w.dtypes) if c not in id_cols and pl.datatypes.is_numeric(dt)]
        mean_cols = [c for c in num_cols if c not in sum_cols]

        agg_exprs = [pl.col(c).sum().alias(c) for c in sum_cols] + [pl.col(c).mean().alias(c) for c in mean_cols]
        w_year = w.group_by(["join_key", "year"]).agg(agg_exprs)
        merged = w_year.join(i, on=["join_key", "year"], how="inner" if drop_unmatched else "left")
    else:
        # Monthly: keep monthly weather; join insurance on key+year (replicate values across months)
        merged = w.join(i, on=["join_key", "year"], how="inner" if drop_unmatched else "left")

    return merged

In [68]:

merged_dataset = merge_and_prepare_polars(fixed_lagged_weather, filtered_insurance, join_grain="monthly")
merged_dataset = merged_dataset.unique()
print(merged_dataset.shape)

(20178, 121)

In [69]:

merged_dataset.tail()

shape: (5, 121)
┌─────────────┬──────┬───────┬───────────┬───┬─────────────┬────────────┬─────────────┬────────────┐
│ location    ┆ year ┆ month ┆ ppt_total ┆ … ┆ commodity_y ┆ loss_ratio ┆ county_stat ┆ net_report │
│ ---         ┆ ---  ┆ ---   ┆ ---       ┆   ┆ ear         ┆ ---        ┆ e           ┆ ed_quantit │
│ str         ┆ i64  ┆ i8    ┆ f64       ┆   ┆ ---         ┆ f64        ┆ ---         ┆ y          │
│             ┆      ┆       ┆           ┆   ┆ i64         ┆            ┆ str         ┆ ---        │
│             ┆      ┆       ┆           ┆   ┆             ┆            ┆             ┆ i64        │
╞═════════════╪══════╪═══════╪═══════════╪═══╪═════════════╪════════════╪═════════════╪════════════╡
│ Pottawattam ┆ 2018 ┆ 8     ┆ 177.0     ┆ … ┆ 2018        ┆ 0.0        ┆ Pottawattam ┆ 294        │
│ ie,IA       ┆      ┆       ┆           ┆   ┆             ┆            ┆ ie,IA       ┆            │
│ Livingston, ┆ 2018 ┆ 11    ┆ 60.1      ┆ … ┆ 2018        ┆ 0.0        ┆ Livingston, ┆ 37         │
│ IL          ┆      ┆       ┆           ┆   ┆             ┆            ┆ IL          ┆            │
│ Iroquois,IL ┆ 2016 ┆ 10    ┆ 67.63     ┆ … ┆ 2016        ┆ 0.01       ┆ Iroquois,IL ┆ 2169       │
│ Champaign,I ┆ 2016 ┆ 4     ┆ 96.43     ┆ … ┆ 2016        ┆ 0.0        ┆ Champaign,I ┆ 169        │
│ L           ┆      ┆       ┆           ┆   ┆             ┆            ┆ L           ┆            │
│ Livingston, ┆ 2019 ┆ 5     ┆ 191.09    ┆ … ┆ 2019        ┆ 4.9        ┆ Livingston, ┆ 2057       │
│ IL          ┆      ┆       ┆           ┆   ┆             ┆            ┆ IL          ┆            │
└─────────────┴──────┴───────┴───────────┴───┴─────────────┴────────────┴─────────────┴────────────┘

In [70]:
# Create loss column for modeling
# loss_ratio is the target: it represents indemnities/liabilities (loss severity)
# We'll use it directly as 'loss' since it's already a normalized measure

merged_dataset = merged_dataset.with_columns([
    pl.col("loss_ratio").alias("loss")
])

# Drop rows where loss is null (no insurance data available)
merged_dataset = merged_dataset.drop_nulls(subset=["loss"])

print(f"Final dataset shape: {merged_dataset.shape}")
print(f"\nLoss statistics:")
print(f"  Zero losses: {(merged_dataset['loss'] == 0).sum()} ({(merged_dataset['loss'] == 0).sum() / merged_dataset.height * 100:.1f}%)")
print(f"  Non-zero losses: {(merged_dataset['loss'] > 0).sum()} ({(merged_dataset['loss'] > 0).sum() / merged_dataset.height * 100:.1f}%)")
print(f"  Mean loss: {merged_dataset['loss'].mean():.4f}")
print(f"  Median loss: {merged_dataset['loss'].median():.4f}")
print(f"  Max loss: {merged_dataset['loss'].max():.4f}")

merged_dataset.head()

Final dataset shape: (19811, 122)

Loss statistics:
  Zero losses: 11160 (56.3%)
  Non-zero losses: 8651 (43.7%)
  Mean loss: 0.6640
  Median loss: 0.0000
  Max loss: 79.8400

shape: (5, 122)
┌───────────────┬──────┬───────┬───────────┬───┬────────────┬───────────────┬───────────────┬──────┐
│ location      ┆ year ┆ month ┆ ppt_total ┆ … ┆ loss_ratio ┆ county_state  ┆ net_reported_ ┆ loss │
│ ---           ┆ ---  ┆ ---   ┆ ---       ┆   ┆ ---        ┆ ---           ┆ quantity      ┆ ---  │
│ str           ┆ i64  ┆ i8    ┆ f64       ┆   ┆ f64        ┆ str           ┆ ---           ┆ f64  │
│               ┆      ┆       ┆           ┆   ┆            ┆               ┆ i64           ┆      │
╞═══════════════╪══════╪═══════╪═══════════╪═══╪════════════╪═══════════════╪═══════════════╪══════╡
│ Saline,MO     ┆ 2020 ┆ 7     ┆ 160.79    ┆ … ┆ 0.0        ┆ Saline,MO     ┆ 2919          ┆ 0.0  │
│ Champaign,IL  ┆ 2022 ┆ 3     ┆ 119.36    ┆ … ┆ 0.0        ┆ Champaign,IL  ┆ 2876          ┆ 0.0  │
│ Pottawattamie ┆ 2024 ┆ 3     ┆ 53.18     ┆ … ┆ 0.0        ┆ Pottawattamie ┆ 188           ┆ 0.0  │
│ ,IA           ┆      ┆       ┆           ┆   ┆            ┆ ,IA           ┆               ┆      │
│ Renville,MN   ┆ 2021 ┆ 9     ┆ 90.38     ┆ … ┆ 0.25       ┆ Renville,MN   ┆ 57755         ┆ 0.25 │
│ Iroquois,IL   ┆ 2022 ┆ 6     ┆ 54.73     ┆ … ┆ 0.0        ┆ Iroquois,IL   ┆ 34            ┆ 0.0  │
└───────────────┴──────┴───────┴───────────┴───┴────────────┴───────────────┴───────────────┴──────┘

In [72]:
# Save the final merged dataset for modeling (as pandas-compatible CSV for the existing modeling code)
# Convert to pandas for compatibility with the existing modeling.ipynb
output_path = "C:\\Users\\Arnold\\OneDrive\\Desktop\\CAPSTONE PROJECT\\farming_risk_regions\\data\\processed\\merged_weather_insurance_data.csv"

# Convert Polars to pandas for the modeling notebook
merged_dataset_pd = merged_dataset.to_pandas()
merged_dataset_pd.to_csv(output_path, index=False)

print(f"Saved merged dataset to: {output_path}")
print(f"  Shape: {merged_dataset_pd.shape}")
print(f"  Columns: {list(merged_dataset_pd.columns[:10])}... ({len(merged_dataset_pd.columns)} total)")

Saved merged dataset to: C:\Users\Arnold\OneDrive\Desktop\CAPSTONE PROJECT\farming_risk_regions\data\processed\merged_weather_insurance_data.csv
  Shape: (19811, 122)
  Columns: ['location', 'year', 'month', 'ppt_total', 'rainy_days', 'ppt_variance', 'tmax', 'tmin', 'temp_range', 'tmax30']... (122 total)